<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Allure.Net.Commons" Version="2.14.1" />
		<PackageReference Include="Allure.NUnit" Version="2.14.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
		<PackageReference Include="Selenium.Support" Version="4.40.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.40.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="144.0.7559.9600" />
		<PackageReference Include="SeleniumExtras.WaitHelpers" Version="1.0.2" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Shouldly" Version="4.3.0" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="appsettings.json" Link="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="allureConfig.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>